### ISSUE TITLE
Rename image and serve it from your localhost

### ISSUE THREAD

**Issue by thujone** [mayabowman/news-app#12]
https://github.com/mayabowman/news-app/blob/d7ccb2b8345b5312c68dfdb5955f2833b2b376e8/styles.css#L28

It's generally considered a bad practice to rely on someone else's website to get a graphic. People do it all the time, but it's not something a web professional would do. You should probably serve it from your localhost and maybe give it a name that's not so crazy.

**Comment by mayabowman** [comment]
fixed
