### ISSUE TITLE
Move variables to tops of functions

### ISSUE THREAD

**Issue by thujone** [mayabowman/news-app#5]
https://github.com/mayabowman/news-app/blob/d7ccb2b8345b5312c68dfdb5955f2833b2b376e8/index.js#L80

Best practice says that variables should be defined at the top of the function whenever possible. Sometimes you have to set the variable value later the function, but you should only define it later when you need to. Also, I notice you have a variable called 'autoDate' which you set to null. It's slightly preferable to declare it with no value rather than set it to null:

`let autoDate;`

**Comment by mayabowman** [comment]
fixed
