### ISSUE TITLE
`searchUrl` instead of `searchURL`

### ISSUE THREAD

**Issue by thujone** [mayabowman/news-app#8]
https://github.com/mayabowman/news-app/blob/d7ccb2b8345b5312c68dfdb5955f2833b2b376e8/index.js#L44

Modern js coding style guides would say to call your variable `searchUrl` instead of `searchURL`. For examples of style guides, check out the two most famous ones:

Idiomatic.js (https://github.com/rwaldron/idiomatic.js/)
AirBnb (https://github.com/airbnb/javascript)

**Comment by mayabowman** [comment]
fixed
